# Generated by Django 4.2.7 on 2023-11-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='updated_ath',
            new_name='updated_at',
        ),
    ]
